### ISSUE TITLE
建议：将ip:端口写入环境变量（纯小白，不知道实际能不能行）

### ISSUE THREAD

**Issue by beicuidewo** [D-Jy-lab/koishi-bingchat-server#1]
我看到程序默认开在8007端口，不过我的服务器有一部分端口并没有放开，所以想着如果能修改程序默认端口的话就好了，然后打开配置文件之后，发现端口写死了（不是用变量的形式，而是直接写了8007这个数字），如果只改我看见的部分的话，我也不太确定会不会有什么地方遗漏导致服务运行不起来，想着如果用环境变量的方式修改的话或许会方便很多，不过我纯小白，我也不知道实际上能否实现，若能采纳，感激不尽

**Comment by djylb** [comment]
已更新教程，参考[README.md](https://github.com/D-Jy-lab/koishi-bingchat-server#readme)说明。
我之前有一版本的提交是支持环境变量的，不过感觉没必要只为这俩参数引入额外包。
docker使用的话直接修改映射端口就行，手动安装直接更改py文件里的参数就好，我新提交在py文件里加入了注释。
