### ISSUE TITLE
后端返回200 OK，机器人回复永远是ERROR

### ISSUE THREAD

**Issue by Arthas-Frost** [D-Jy-lab/koishi-bingchat-server#3]
如题，我再windows上使用Koishi和Pycharm进行了调试，上午时机器人还能正常返回bing的回复，没几条以后无论询问什么回复都变成了ERROR，pycharm内针对询问的运行日志如下

User: From depth I come
INFO:     127.0.0.1:1263 - "POST /bing HTTP/1.1" 200 OK

后端服务器使用地址为 http://127.0.0.1:8006

请问有大佬知道是为什么吗？

**Comment by djylb** [comment]
重新获取一下cookie呢？

**Comment by Arthas-Frost** [comment]
已解决，可能是那两天网络有故障
