### ISSUE TITLE
cookie只需要_U这个参数

### ISSUE THREAD

**Issue by dfaofeng** [D-Jy-lab/koishi-bingchat-server#4]
我在别的项目看到只需要这个_U这个cookie就行了,不需要全部的参数

**Comment by djylb** [comment]
这个问题应该在上游项目[EdgeGPT](https://github.com/acheong08/EdgeGPT)提问。
个人感觉都写上能够低封号风险。
你可以在JSON文件里只粘_U这个cookie试试，需要仿照导出的JSON格式。
